#Anaconda
- 파이썬 통합 개발환경(IDE)
- jupyter notebook 지원
- https://www.anaconda.com/products/individual

#Jupyter notebook
- Windows Powershell (shift+우클릭) / 명령 프롬프트(cmd) / Mac OS X terminal
 실행
- jupyter notebook 입력
- H: 키보드 단축키 설명

## 데이터 처리 및 분석을 위한 파이썬 모듈

1. Numpy: 다차원 배열 생성 및 연산
2. Pandas: Dataframe 생성 및 조작
3. Scipy: 과학 및 공학 연산 --> 통계분석
4. Matplotlib: 시각화


In [ ]:
#  모듈설치

### Windows 명령 프롬프트(cmd), Powershell 
pip install numpy scipy pandas matplotlib --user
### Mac OS 터미널
pip3 install numpy scipy pandas matplotlib
### Jupyter notebook
!pip install numpy scipy pandas matplotlib


# Numpy
Numerical Python<br/><br/>
다차원 배열(multi-dimensional array)을 쉽고 빠르게 처리<br/>
숫자로 이루어진 Table형 데이터를 다룰 때 주로 사용(예: 이미지)<br/>
같은 종류의 data type을 원소로 함<br/>

https://wikidocs.net/14569


###차원에 따라 데이터를 부르는 이름
- 1차원: vector<br/>
- 2차원: matrix<br/>
- 3차원: tensor


In [ ]:
# numpy 호출
import numpy as np

# Ndarray (N-dimensional Array) <b/>
- numpy의 array함수, ...,
- 같은 data type만을 가짐

In [ ]:
# numpy.array(object, [dtype=None, copy=True, order=None, subok=False, ndmin=0])

In [ ]:
import numpy as np
a = [1,2,3,4,5.0]
b = np.array(a)
b

array([1., 2., 3., 4., 5.])

In [ ]:
# list와 ndarray 비교
a = [9,2,5.06,20]
b = np.array(a)
c = np.array(a, dtype="int")
# b
# c
print(type(a),'\n', type(b))

<class 'list'> 
 <class 'numpy.ndarray'>


In [ ]:
# ndarray -> list 변환: tolist()
b.tolist()

[9.0, 2.0, 5.06, 20.0]

In [ ]:
# ndarray 내부 data: int, float, (str), (bool)
# data type: numeric(int, float, complex), str, bool, str, list, tuple, dict, set

a = "abcd"
b = list(a)
c = tuple(a)
d = dict((('a',1), ('b', 2)))
e = set(a)

In [ ]:
#np.array(a)    # dtype = data type, 'U' = 유니코드 약자 = 문자열
#np.array(b)    # 대괄호 [] = 차원
#np.array(c)
#np.array(d)    # object = 객체
#np.array(e)

In [ ]:
# size: 총 원소의 개수
# shape: 차원구조
# ndim : 차원 수
# dtype: 원소의 data type

print(np.array(a).size, np.array(a).shape, np.array(a).ndim, np.array(a).dtype)
print(np.array(b).size, np.array(b).shape, np.array(b).ndim, np.array(b).dtype)
print(np.array(c).size, np.array(c).shape, np.array(c).ndim, np.array(c).dtype)
print(np.array(d).size, np.array(d).shape, np.array(d).ndim, np.array(d).dtype)
print(np.array(e).size, np.array(e).shape, np.array(e).ndim, np.array(e).dtype)

1 () 0 <U4
4 (4,) 1 <U1
4 (4,) 1 <U1
1 () 0 object
1 () 0 object


In [ ]:
arr = np.array([[1,2,3,4],[5,6,7,8]])
# np.array([(1,2,3,4),(5,6,7,8)])
# np.array(([1,2,3,4),(5,6,7,8]))
# np.array(((1,2,3,4),(5,6,7,8)))
arr
print(arr.size, arr.shape, arr.ndim, arr.dtype)
#len(arr)

8 (2, 4) 2 int64


In [ ]:
# ndarray 생성 함수
- numpy.arange:np.arange([start,] stop[, step,], dtype=None)
- numpy.linspace: numpy.linspace(start, stop, [num=50, endpoint=True, retstep=False, dtype=None)])
- numpy.logspace:: log scale

SyntaxError: ignored

In [ ]:
a = np.arange(10)
b = np.arange(1,10.)
c = np.arange(1,10,0.5)
d = np.arange(1,10,3,dtype='float')

In [ ]:
a = np.linspace(1,10)
b = np.linspace(1,np.pi,num=5)
c = np.linspace(1,10, num=5, endpoint = False)
d = np.linspace(1, 10., num=5, retstep=True)  # step 명시
d

In [ ]:
print(np.linspace(0.02, 2, 20))
print(np.logspace(0.02, 2, 20))
np.logspace(np.log10(0.02), np.log10(2), 20)

In [ ]:
# ones, zeros, full, eye(identity)
a = np.ones((2,5))   # default dtype = float
b = np.zeros((2,5),dtype='int')  # default dtpe = float
c = np.full((2,3), 0.5)
d = np.eye(3) # 3 by 3 단위행렬(identity)
dd = np.identity(3)
dd

In [ ]:
# T: transpose (전치) (2,5).T = (5.2)
# reshape: ndarray 차원 변환
#a = np.arange(1,20,2)
#a.reshape(2,5)
#a.shape = (2,5)
#aa= a.reshape(2,5).T
#aa
a = np.arange(1,10).reshape(3,3)
a.T

In [ ]:
# astype: ndarray data type 변환
a = np.arange(0,10,2)

#print(a.dtype)
a.astype('str')   # 자료형 + 비트수
# astype('float' |'str' | 'int' )
# b = a.astype('str')

In [ ]:
# ndarray 연산
a = np.arange(1,10).reshape(3,3)
a

In [ ]:
#a + [2]
# a * 2
#a + [1,2]
# a - a
# a * a
# a * [14]
# a * [1,2,3]
# a / (a+1)
# a % [1,2,3]
# a + [4,5]
# a.tolist() + [1,2,3]

In [ ]:
# 행렬 곱 첫번째 matrix 열 = 두번째 matrix 행
aa = np.arange(10).reshape(5,2)
bb = np.arange(10).reshape(2,5)
#aa @ bb
np.dot(aa,bb) # 내적

In [ ]:
# indexing, slicing: 1차원
a = np.arange(1,8)
a
#1,2,3,4,5,6,7
#0 1 2 3 4 5 6
# a[5]
# a[1:3]
# a[1] = 0
# a[1:3] = [10, 100]
# a[1:3] = [10,100]; a
# a[1:3] = [1]
a[1:3] = [1,2,3]

In [ ]:
# Step: 1차원
#[start:end:step]
#step 양수: 왼쪽 -> 오른쪽
#음수 오른쪽 -> 왼쪽
a = np.arange(1,10,2)
#1,3,5,7,9
#0 1 2 3 4
#-5  -4  -3  -2 -1
# a[::]
# a[::2] 
# a[::-1]
# a[::-2]
a[-2::-1]
# a[2::-1]

In [ ]:
# indexing, slicing: 2차원
a = np.arange(1,13).reshape(3,4)

# a[-3]
# a[0][-1]
# a[-1][0]
# a[0:2]
# a[0:1]
# a[0:2][0]
# a[0:2][0][1:]

In [ ]:
# Step: 2차원
a = np.arange(1,13).reshape(3,4)
# a[::2]
# a[::-1]
# a[1::-1]
# a[::2][1]
# a[::2][1:2]
a[::2][::2]


In [ ]:
# row&column indexing, slicing
a = np.arange(1,13).reshape(3,4)
# a[0][1]
# a[0,1]
# a[0:2][1]
# a[0:2,1]
# a[:][:-1]
# a[:,:-1]
# a[0,]

In [ ]:
a = np.arange(1,13).reshape(3,4)
a[0:2,0]

array([1, 5])

In [ ]:
# 2차원 ndarray 값 변경
a = np.arange(1,9).reshape(2,4)
a
# a[0] = 100; a
# a[0] = [100]; a
# a[0] = [10,20,30,40]; a
# a[0] = np.linspace(10,30,num=4); a

In [ ]:
b = np.arange(20).reshape(4,5)
# b[0:2] = 12; b
# b[0:2] = np.arange(12,17); b
# b[0:2] = np.arange(20,30); b
# b[0:2] = np.arange(20,30).reshape(2,5); b

In [ ]:
c = np.arange(1,13).reshape(3,4)
# c[0:2,0:2] = 5; c
# c[0:2,0:3] = [11,12,13]; c
# c[1:, 1:] = np.array([[2,4,8],[16,32,64]]);c

In [ ]:
# squeeze: remove axes of length one
a = np.arange(16).reshape(4,1,4)
a
b = np.squeeze(a)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [ ]:
# 조건검색
a = np.arange(2,20,2).reshape(3,3); a
#a == 10
a[a==10] = 100
a

array([[  2,   4,   6],
       [  8, 100,  12],
       [ 14,  16,  18]])

In [ ]:
# numpy.random
# seed: pseudo random 상태 설정, 난수 정해진 순서대로
# shuffle: 조합
# choice: 순열
# rand: uniform distribution
# randn: Gaussian noraml distribution

np.random.seed(0)
x = np.arange(10)
np.random.shuffle(x)
#np.random.choice(x)
x

array([2, 8, 4, 9, 1, 6, 7, 3, 0, 5])

In [ ]:
# np.random.rand(차원,..): [0,1)
a = np.random.rand()  # [0,1) 실수 하나
b = np.random.rand(5) # shape: (5,)
c = np.random.rand(2,5) # shape: (2,5)
d = np.random.rand(3,2,6) # shape: (3,2,6)
b

array([0.24442559, 0.15896958, 0.11037514, 0.65632959, 0.13818295])

In [ ]:
# np.random.randn(차원,..): mean=0, variance=1 표준정규분포
a = np.random.randn() # 실수 하나
b = np.random.randn(5) # (5,)
c = np.random.randn(2,5) 
d = np.random.randn(3,2,6)

In [ ]:
# np.random.randint(low, [high=None, size=None, dtype=int])
a = np.random.randint(10) # [0,10) discrete uniform
b = np.random.randint(1,10,(3,3)) 
b

array([[3, 9, 7],
       [7, 2, 7],
       [9, 9, 4]])

In [ ]:
# np.cumsum(a, [axis=None, dtype=None, out=None]): cumulative sum
(#np.cumprod: cumulative product)
# row: axis = 0  
# column: axis = 1

In [ ]:
arr = np.array([[1,2,3],[4,5,6]])
arr
#np.cumsum(arr)
# np.cumsum(arr, axis=0)
# np.cumsum(arr, axis=1)
# np.cumprod(arr)

array([[1, 2, 3],
       [5, 7, 9]])

In [ ]:
# ravel(), flatten(), reshape(-1): 다차원 -> 1차원
a = np.arange(1,5).reshape(2,2)
  # row 기준

# a.ravel('F')  # column 기준
# a.flatten(), a.flatten('F')
rav = a.ravel()
res = a.reshape(-1)
flat = a.flatten() # 1차원배열을 복사함, 원본 데이터 변경에 영향받지 않음
a

array([[1, 2],
       [3, 4]])

In [ ]:
a[0,0] = 0
# rav
#res
flat

array([1, 2, 3, 4])

In [ ]:
# ndarray 참조만 할당
a = np.array([[1,1],[2,2], [3,3]])
b = a[1:]
a[1,1] = 0 
print(id(a), id(b))
# a
# b 
# c = a.copy()  # a와 독립적

139649573834800 139649573717648


In [ ]:
# np.concatenate([arr1, arr2, ], axis = 0) # row(0): default, column(1)
a = np.array([[1,2,3], [4,5,6]])
b = np.array([[7,8,9], [10,11,12]])
c = np.array([[1],[2]])
# np.concatenate([a,b])
np.concatenate([a,b,c], axis=1)

array([[ 1,  2,  3,  7,  8,  9,  1],
       [ 4,  5,  6, 10, 11, 12,  2]])

In [ ]:
# repeat(array 개별 원소 반복횟수, [axis=])
import numpy as np
a = np.arange(4)
a.repeat(3)
a.repeat([1,2,3,4])
b = np.random.randint(1,10,(2,3))
b
#b.repeat([2,3],axis=0)
b.repeat([1,2,3],axis=1)


array([[2, 3, 3, 3, 3, 3],
       [9, 2, 2, 6, 6, 6]])

In [ ]:
# np.tile(ndarray, shape)
b = np.random.randint(1,10,(2,3))
b
# np.tile(b,2)   # (2,)
# np.tile(b, (2,1))
# np.tile(b, (2,2,2))

array([[3, 6, 8],
       [8, 7, 2],
       [3, 6, 8],
       [8, 7, 2]])

In [ ]:
# Agrregate function 
a = np.arange(16).reshape(4,4)
# a.sum()   # np.sum(a)
# a.sum(0)  # 각 coulumn별 합계값, np.sum(a,0)
# a.sum(1)  # 각 row별 합계값, np.sum(a,1)
# a.mean()   # np.mean(a)
# a.mean(0)    # column
# a.mean(1)    # row
# a.min(0)
# a.max(0)
# a.std(0)
# np.median(a)   # 메서드 불가능 (a.median()불가)

array([ 6, 22, 38, 54])

In [ ]:
# np.append(ndarray, 추가할 값): 1차원으로 출력
# np.array(ndarray1, ndarray2, axis=): ndarray1과 ndarray2 차원이 같아야 함
a = np.arange(16).reshape(4,4)
# np.append(a, -10)
# np.append(a, np.arange(4).reshape(2,2))
# np.append(a, a[:1], axis=0)
# np.append(a, np.arange(4).reshape(4,1),axis=1)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,  0,
        1,  2,  3])

In [ ]:
# sort()
a = np.random.rand(2,4)
a
#a.sort(); a  # 행별 오름차순
#a[:,::-1]  #행별 내림차순
#b = np.random.randn(4,2)
b.sort(0); b   # 열별 오름차순
b[::-1,:]   #열별 내림차순


array([[ 1.18802979,  0.84436298],
       [ 0.94942081,  0.31694261],
       [-1.00021535,  0.08755124],
       [-1.22543552, -1.5447711 ]])

In [ ]:
# ndarray 파일 입출력
# np.savetxt(fname, X, fmt='%.18e', delimiter=' ', newline='\n', header='', footer='', comments='# ', encoding=None)
# np.loadtxt(fname, dtype=float, comments='#', delimiter=None, converters=None, skiprows=0, usecols=None, unpack=False, ndmin=0, encoding='bytes', max_rows=None, *, like=None)
a = np.random.rand(3,2)

np.savetxt('out.txt', a, fmt = '%.4f', delimiter='\t')
np.loadtxt('out.txt', dtype='float', delimiter = '\t')

array([[0.6699, 0.7852],
       [0.2817, 0.5864],
       [0.064 , 0.4856]])

In [ ]:
# 연립방정식 해 구하기

# x+y-z=0, 2x-y+3z=9, x+2y+z=8
A = np.linalg.inv(np.array([[[1,1,-1],[2,-1,3],[1,2,1]]]))  #np.linalg.inv: 역행렬
B = np.array([0,9,8])
C = np.dot(A,B); C  # np.dot : 행렬의 곱
