In [15]:
import pandas as pd
passengers = pd.read_csv("train.csv")
print(passengers.shape)
print(passengers.head())

(891, 12)
   PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN    

In [16]:
passengers['Sex'] = passengers['Sex'].map({'female':1,'male':2})
passengers['Age'].fillna(value=passengers['Age'].mean(), inplace=True)

passengers['FirstClass'] = passengers['Pclass'].apply(lambda x: 1 if x == 1 else 0)
passengers['SecondClass'] = passengers['Pclass'].apply(lambda x: 1 if x == 2 else 0)
passengers['ThirdClass'] = passengers['Pclass'].apply(lambda x: 1 if x == 3 else 0)

In [17]:
passengers.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name  Sex   Age  SibSp  Parch  \
0                            Braund, Mr. Owen Harris    2  22.0      1      0   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...    1  38.0      1      0   
2                             Heikkinen, Miss. Laina    1  26.0      0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)    1  35.0      1      0   
4                           Allen, Mr. William Henry    2  35.0      0      0   

             Ticket     Fare Cabin Embarked  FirstClass  SecondClass  \
0         A/5 21171   7.2500   NaN        S           0            0   
1          PC 17599  71.2833   C85        C           1            0   
2  STON/O2. 3101282   7.9250   NaN        S           0            0   
3            113803  53.1000  C123        S           1            0   
4            373450   8.0500   NaN        S           0            0   

   ThirdClass  
0           1  
1           0  
2           1  
3           0  
4           1

In [18]:
features = passengers[['Sex', 'Age', 'FirstClass', 'SecondClass', 'ThirdClass', 'Fare']]
survival = passengers['Survived']

In [19]:
features.head()

Sex   Age  FirstClass  SecondClass  ThirdClass     Fare
0    2  22.0           0            0           1   7.2500
1    1  38.0           1            0           0  71.2833
2    1  26.0           0            0           1   7.9250
3    1  35.0           1            0           0  53.1000
4    2  35.0           0            0           1   8.0500

In [20]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_text = train_test_split(features, survival, test_size = 0.2, random_state = 5)

In [21]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)

In [23]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression()
model.fit(x_train, y_train)

LogisticRegression()

In [25]:
print(model.score(x_train, y_train))

0.797752808988764


In [27]:
print(model.score(x_test, y_text))


0.8268156424581006


In [28]:
print(model.coef_)

[[-1.26608506 -0.43521793  0.5659016   0.07778033 -0.55509175 -0.10607599]]


In [41]:
import numpy as np

Jack = np.array([2.0, 20.0, 0.0, 0.0, 1.0, 10.0])
Rose = np.array([1.0, 17.0, 1.0, 0.0, 0.0, 50.0])
ME = np.array([2.0, 25.0, 1.0, 0.0, 0.0, 75.0])

sample_passengers = np.array([Jack, Rose, ME])

sample_passengers = scaler.transform(sample_passengers)

/Users/jojuhyeon/opt/anaconda3/envs/parrot/lib/python3.9/site-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


In [42]:
print(model.predict(sample_passengers))

[0 1 1]


In [43]:
print(model.predict_proba(sample_passengers))

[[0.88874619 0.11125381]
 [0.04808431 0.95191569]
 [0.49588321 0.50411679]]
